### ISSUE TITLE
rename "information" page to "travel"

### ISSUE THREAD

**Issue by lheagy** [geoscixyz/3dem-7#34]
I am getting a number of emails with folks asking about hotels, which makes me think that people might not be finding this page. Do you think that renaming it to "travel" would help it be more discoverable?

**Comment by santisoler** [comment]
Thanks @lheagy. You're right, that page is only accessible through the "information" link in the top bar. But given that we also have an Information section in the home page people might think we are just linking to that section. I'll rename the page and add a link in the Information section in the home page. 

Also, should we rethink the links in the navbar? Maybe it's a little bit confusing having link to sections in home and other pages at the same level.
